/**
 * This package contains immutable value objects generated by the https://immutables.github.io/
 * library. The interfaces in this package are implemented through annotation processing and can be
 * found in the folder target/generated-sources/annotations.
 */
@org.immutables.value.Value.Style(depluralize = true)
package seanizer.json.organizer.value;

